In [1]:
# 필요한 library
import tensorflow as tf
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.losses import mse 

In [2]:
# 시드 설정
tf.random.set_seed(777)

In [22]:
# 데이터 준비하기
x = np.array([[0,0],[1,0],[0,1],[1,1]])
y = np.array([[0],[1],[1],[1]])

print(x)
print(y)

[[0 0]
 [1 0]
 [0 1]
 [1 1]]
[[0]
 [1]
 [1]
 [1]]


In [23]:
# type이 tensor 자료형인지 확인하자. * tensor 자료형: float, int, complex 등
print(x.dtype)
print(y.dtype)

int64
int64


In [24]:
# 단층 퍼셉트론 구성하기
model = Sequential([
                    Dense(1, input_dim=2, activation='linear')
])

In [25]:
# 모델 구조 보기
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 1)                 3         
                                                                 
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [26]:
# 모델 준비하기
model.compile(optimizer = SGD(), loss = mse, metrics = ['acc']) #list 형태로 metric 찍기

In [31]:
# 모델 학습하기
model.fit(x, y, epochs= 100)

Epoch 1/100
1/1 [==============================] - 0s 9ms/step - loss: 0.2389 - acc: 0.7500
Epoch 2/100
1/1 [==============================] - 0s 8ms/step - loss: 0.2375 - acc: 0.7500
Epoch 3/100
1/1 [==============================] - 0s 6ms/step - loss: 0.2361 - acc: 0.7500
Epoch 4/100
1/1 [==============================] - 0s 5ms/step - loss: 0.2347 - acc: 0.7500
Epoch 5/100
1/1 [==============================] - 0s 5ms/step - loss: 0.2334 - acc: 0.7500
Epoch 6/100
1/1 [==============================] - 0s 5ms/step - loss: 0.2320 - acc: 0.7500
Epoch 7/100
1/1 [==============================] - 0s 5ms/step - loss: 0.2308 - acc: 0.7500
Epoch 8/100
1/1 [==============================] - 0s 5ms/step - loss: 0.2295 - acc: 0.7500
Epoch 9/100
1/1 [==============================] - 0s 5ms/step - loss: 0.2282 - acc: 0.7500
Epoch 10/100
1/1 [==============================] - 0s 5ms/step - loss: 0.2270 - acc: 0.7500
Epoch 11/100
1/1 [==============================] - 0s 5ms/step - loss: 0.2258 

In [32]:
# 새로운 데이터 결과 예측
x_t=np.array([[1,0],[0,0],[1,1],[0,1]])

model.predict(x_t)

array([[0.8107714 ],
       [0.7373272 ],
       [0.9104623 ],
       [0.83701813]], dtype=float32)

In [33]:
# 새로운 데이터 결과 예측2
x_o=np.array([[0,0],[1,0],[0,1],[1,1]])

model.predict(x_o)

array([[0.7373272 ],
       [0.8107714 ],
       [0.83701813],
       [0.9104623 ]], dtype=float32)