In [8]:
# 필요한 library
import tensorflow as tf
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.losses import mse 

In [9]:
# 시드 설정
tf.random.set_seed(777)

In [10]:
# 데이터 준비하기
x = np.array([[0,0],[1,0],[0,1],[1,1]])
y = np.array([[0],[1],[1],[0]])

print(x)
print(y)

[[0 0]
 [1 0]
 [0 1]
 [1 1]]
[[0]
 [1]
 [1]
 [0]]


In [11]:
# type이 tensor 자료형인지 확인하자. * tensor 자료형: float, int, complex 등
print(x.dtype)
print(y.dtype)

int64
int64


In [12]:
# 단층 퍼셉트론 구성하기
model = Sequential([
                    Dense(32, input_dim=2, activation='relu'), #hidden layer
                    Dense(1, activation='sigmoid')
])

In [13]:
# 모델 구조 보기
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 32)                96        
                                                                 
 dense_3 (Dense)             (None, 1)                 33        
                                                                 
Total params: 129
Trainable params: 129
Non-trainable params: 0
_________________________________________________________________


In [14]:
# 모델 준비하기
model.compile(optimizer = RMSprop(learning_rate=0.01), loss = mse, metrics = ['acc']) #list 형태로 metric 찍기

In [15]:
# 모델 학습하기
model.fit(x, y, epochs= 100)

Epoch 1/100
1/1 [==============================] - 1s 789ms/step - loss: 0.2646 - acc: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 12ms/step - loss: 0.2474 - acc: 0.2500
Epoch 3/100
1/1 [==============================] - 0s 11ms/step - loss: 0.2351 - acc: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 13ms/step - loss: 0.2273 - acc: 0.7500
Epoch 5/100
1/1 [==============================] - 0s 13ms/step - loss: 0.2211 - acc: 0.7500
Epoch 6/100
1/1 [==============================] - 0s 12ms/step - loss: 0.2148 - acc: 0.7500
Epoch 7/100
1/1 [==============================] - 0s 13ms/step - loss: 0.2100 - acc: 1.0000
Epoch 8/100
1/1 [==============================] - 0s 11ms/step - loss: 0.2047 - acc: 0.7500
Epoch 9/100
1/1 [==============================] - 0s 17ms/step - loss: 0.1987 - acc: 1.0000
Epoch 10/100
1/1 [==============================] - 0s 16ms/step - loss: 0.1935 - acc: 1.0000
Epoch 11/100
1/1 [==============================] - 0s 17ms/step - l

In [16]:
# 새로운 데이터 결과 예측
x_t=np.array([[1,0],[0,0],[1,1],[0,1]])

model.predict(x_t)

array([[0.96574736],
       [0.26287466],
       [0.03063524],
       [0.96963024]], dtype=float32)

In [17]:
# 새로운 데이터 결과 예측2
x_o=np.array([[0,0],[1,0],[0,1],[1,1]])

model.predict(x_o)

array([[0.26287466],
       [0.96574736],
       [0.96963024],
       [0.03063524]], dtype=float32)